const cuisines = [
  "African",
  "Asian",
  "American",
  "British",
  "Cajun",
  "Caribbean",
  "Chinese",
  "Eastern European",
  "European",
  "French",
  "German",
  "Greek",
  "Indian",
  "Irish",
  "Italian",
  "Japanese",
  "Jewish",
  "Korean",
  "Latin American",
  "Mediterranean",
  "Mexican",
  "Middle Eastern",
  "Nordic",
  "Southern",
  "Spanish",
  "Thai",
  "Vietnamese",
];

const diet = [
  "Gluten Free",
  "Ketogenic",
  "Vegetarian",
  "Lacto-Vegetarian",
  "Ovo-Vegetarian",
  "Vegan",
  "Pescetarian",
  "Paleo",
  "Primal",
  "Low FODMAP",
  "Whole30",
];

const intolarances = [
  "Dairy",
  "Egg",
  "Gluten",
  "Grain",
  "Peanut",
  "Seafood",
  "Sesame",
  "Shellfish",
  "Soy",
  "Sulfite",
  "Tree Nut",
  "Wheat",
];

const meal_types = [
  "breakfast",
  "bread",
  "drink",
  "snack",
  "appetizer",
  "soup",
  "salad",
  "side dish",
  "main course",
  "dessert",
  "sauce",
  "beverage",
  "marinade",
  "fingerfood",
];
const recipeSortingGrouped = {
  general: [
    "(empty)",
    "meta-score",
    "popularity",
    "healthiness",
    "price",
    "time",
    "random",
  ],
  ingredients: ["max-used-ingredients", "min-missing-ingredients"],
  nutrients: [
    "alcohol",
    "caffeine",
    "copper",
    "energy",
    "calories",
    "calcium",
    "carbohydrates",
    "carbs",
    "choline",
  ],
  fats: [
    "cholesterol",
    "total-fat",
    "trans-fat",
    "saturated-fat",
    "mono-unsaturated-fat",
    "poly-unsaturated-fat",
  ],
  vitamins: [
    "vitamin-a",
    "vitamin-b1",
    "thiamin",
    "vitamin-b2",
    "riboflavin",
    "vitamin-b3",
    "niacin",
    "vitamin-b5",
    "pantothenic-acid",
    "vitamin-b6",
    "vitamin-b12",
    "vitamin-c",
    "vitamin-d",
    "vitamin-e",
    "vitamin-k",
  ],
  minerals: [
    "fluoride",
    "iodine",
    "iron",
    "magnesium",
    "manganese",
    "phosphorus",
    "potassium",
    "selenium",
    "sodium",
    "zinc",
  ],
  others: ["fiber", "folate", "folic-acid", "protein", "sugar"],
};

module.exports = {
  cuisines,
  diet,
  intolarances,
  meal_types,
  recipeSortingGrouped,
};
